/*!
 * @file
 *
 * @brief Frequency Detection framework
 *
 * @author ECE40X Senior Project
            Guitar Tuner
 * @author Ryan Dufour
 * @author Phil Robb
 *
 * @date Oct 2, 2018
 *
 * Board file for Lab 1, this is the code that gets flashed to board
 * this uses the example code provided by Hummels and the
 * ECE department.
 * we simply called our task functions in this code
 *This is implementing the arm_FIR functions on the board
 */

#include "stm32l4xx_hal.h"
#include "stm32l476g_discovery.h"
#include "ece486.h"
#include <stdlib.h>
#include <stdio.h>
#include "arm_math.h"
#include <math.h>
#include "UART.c"

#define FFT_len 1024
#define decimation 20
#define BL 4
extern FlagStatus KeyPressed;   // Use to detect button presses
uint8_t buffer[BufferSize];

int main(void)
{

  int nsamp, i, n, j;
  float avg, dev;
  float *input, *output1, *output2, *outputFin;
  static float sign=1.0;
  static int button_count = 0;
  char lcd_str[8];
  arm_rfft_fast_instance_f32 *fftStruct;

  nsamp = 1024;


  /*
   * Set up ADCs, DACs, GPIO, Clocks, DMAs, and Timer
   *
   * If your discovery board has been modified to support the external
   * HSE reference, use the (better quality crystal controlled) HSE
   * configuration.  If not, you can use the MSI reference, and things
   * should still work -- but your clocks will drift over time.
   *
   * The MSI (Medium speed internal) reference is the on-chip RC oscillator
   *
   * The HSE (High speed external) reference is an external clock, either
   * provided through the external connector, or (if your board is modified)
   * from the crystal reference source generated by the other processor
   * on the development board.
   */
  setblocksize(nsamp);
  initialize_ece486(FS_10K, MONO_IN, MONO_OUT, MSI_INTERNAL_RC);
  UART2_Init();
  //initialize_ece486(FS_10K, MONO_IN, MONO_OUT, HSE_EXTERNAL_8MHz);

  /*
   * Allocate Required Memory
   */
  n = 1;
  avg = 1.0;

  arm_rfft_fast_init_f32(fftStruct, FFT_len);



  input = (float *)malloc(sizeof(float)*nsamp);
  output1 = (float *)malloc(sizeof(float)*nsamp);
  output2 = (float *)malloc(sizeof(float)*nsamp);
  //outputFin = (float *)malloc(sizeof(float)*nsamp);

  if (input==NULL || output1==NULL || output2==NULL) {
    flagerror(MEMORY_ALLOCATION_ERROR);
    while(1);
  }

   /*
   * Normally we avoid printf()... especially once we start actually
   * processing streaming samples.  This is here to illustrate the
   * use of printf for debugging programs.
   *
   * To see the printf output, connect to the ST-Link serial port.
   * Use: 115200 8N1
   */
  // printf("Starting execution using %d samples per input block.\n",nsamp);

  /*
   * Infinite Loop to process the data stream, "nsamp" samples at a time
   */
  while(1){





    /*
     * Ask for a block of ADC samples to be put into the working buffer
     *   getblock() will wait here until the input buffer is filled...  On return
     *   we work on the new data buffer... then return here to wait for
     *   the next block
     */

    /*
     * signal processing code to calculate the required output buffers
     */



    DIGITAL_IO_SET(); 	// Use a scope on PD0 to measure execution time
    getblock(input);

    //putblock(input);

    //this will also keep track of how many blocks collected
    //since decimating we will need #D blocks until FFT is full
    arm_rfft_fast_f32(fftStruct, input, output1, 0);

    arm_cmplx_mag_squared_f32(output1, output2, nsamp);

    arm_rfft_fast_f32(fftStruct, output2, output1, 1);



    /* Normalize signal*/
    /* since we performed Autocorrelation, the signal energy is located at origin */
      for(i=0;i<nsamp;i++){

         output1[i] /= output1[0];

      }


    /* zero out negative correlations */
      for(i=0;i<nsamp;i++){

         if(output1[i]<0) output1[i] = 0;

      }

      arm_mean_f32(output1, nsamp,  &avg);
      arm_std_f32(output1, nsamp, &dev);

      /*look only at peaks above the deviation threshold */
      /*helps with false positives */
        for(i=0; i<nsamp; i++){

          if(output1[i]<(avg+dev)) output1[i] = 0;
      }






    DIGITAL_IO_RESET();	// (falling edge....  done processing data )






        /* this is the conversion for the A201 */
      //  n = sprintf((char *)buffer, "Average = %f\t\r\n", (a-0.002691)/0.004566);

      /* this is the conversion for A401
      1/0.21144 = 4.73 approx, multiplies are cheaper */
      /*0.44f is the DC offset of ADC, maybe. Subtract it to get accurate reading */
        n = sprintf((char *)buffer, "Average = %f\t\r\n", avg);
    		//n += sprintf((char *)buffer + n, "Equivalent Voltage = %f\r\n", a);
    		USART_Write(USART2, buffer, n);




    if (KeyPressed) {
      KeyPressed = RESET;
      sign *= -1.0;		// Invert output1

      /*
       * On each press, modify the LCD display, and toggle an LED
       * (LED4=red, LED5=green) (Red is used to show error conditions)
       *
       * Don't be surprised when these cause a Sample Overrun error,
       * depending on your sample rate.
       */
      button_count++;
      sprintf(lcd_str, "BTN %2d", button_count);
      BSP_LCD_GLASS_DisplayString( (uint8_t *)lcd_str);
      BSP_LED_Toggle(LED5);
    }
  }
}
